project:
  type: website
  output-dir: docs

website:
  title: "Learning Client-Side Web Security - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cross-site-scripting.qmd
      - cross-site-request-forgery.qmd
      - cross-origin-resource-sharing.qmd
      - clickjacking.qmd
      - dom-based-vulnerabilities.qmd
      - websockets.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
