project:
  type: website
  output-dir: docs

website:
  title: "Learning Web Security - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - server-side-web-security.qmd
        text: Server-Side Web Security  
      - client-side-web-security.qmd
        text: Client-Side Web Security

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
